### ISSUE TITLE
Request signature does not match the Signing Mechanism vs Request values

### ISSUE THREAD

**Issue by julianbueno** [Shopify/hosted-payment-sim#16]
Hi

what are the values being considered by the request signing mechanism 

the attached example is giving me: "334afa5d86d80cd5b4b3488bccd5c50b4e43dab7d595cc8e63732c3578c55012"

![2015-06-10 17_25_29-offsite gateway sim shopify](https://cloud.githubusercontent.com/assets/4759954/8077343/4f4b6b0c-0f98-11e5-89a0-5ddca09d5abf.png)

if I do it I'm getting

"a1fed8096b305795d4388a4838b042abeb0e4fc53d4a4c0c01c89f0590ff494b"

The following fields are not being considered in the offsite gateway sim
x_transaction_type
x_timestamp

The following fields are not being considered in the request calculator
x_customer_shipping_first_name
x_customer_shipping_last_name

**Comment by julianbueno** [comment]
If I use the calculator fileds I got 
"6692dac6b5deab91b1aaa8e70e728f0c0da221029a280911e6d02cc7635da50c" which match

![2015-06-10 18_18_10-offsite gateway sim shopify](https://cloud.githubusercontent.com/assets/4759954/8078263/c86a1ce8-0f9f-11e5-8965-228247fd3470.png)

**Comment by andrewpaliga** [comment]
@julianbueno all the code the calculator uses is in this repo. The signature is generate [here](https://github.com/Shopify/offsite-gateway-sim/blob/master/app.rb#L30). I believe all values starting with `x_` are used.

**Comment by julianbueno** [comment]
@andrewpaliga 

when you guys send the POST to the POST url
![2015-06-11 10_02_37-zipmoney payments shopify](https://cloud.githubusercontent.com/assets/4759954/8097015/1556974e-1021-11e5-8b93-6e288323fa80.png)

you are missing 

x_transaction_type
x_timestamp

if I want to verify in my side the signature I have mismatch

can you please add all the 'x_' fields in your POST

**Comment by andrewpaliga** [comment]
@julianbueno it does appear these fields are missing. They shouldn't be required however as all transactions will be sales. Can you generate signature similar to how it being done here: https://github.com/Shopify/offsite-gateway-sim/blob/master/app.rb#L40 ?

**Comment by julianbueno** [comment]
@andrewpaliga 

From the code here http://repl.it/uRL/1 it is clear that you can't get the same signature from the fields that Shopify sent in the payload

**Comment by andrewpaliga** [comment]
@julianbueno can you try with the same values in our calculator? https://offsite-gateway-sim.herokuapp.com/calculator

I get `3b9b2addf4c7ac299013db07c01dfb163261b3a7e7d1c073ee82065a8909d6df` with your code

**Comment by julianbueno** [comment]
@andrewpaliga 

The Shopify store is sending us the exact same message that is in the code example i supplied and they are sending a x_signature="5fb18d05e24d08b1c94037dd4ce3474912f53568e5b6a7898b94a76980d02d3f"

You are correct that when we do the calculation using the code i have supplied we are getting "3b9b2addf4c7ac299013db07c01dfb163261b3a7e7d1c073ee82065a8909d6df"

So it looks like the Shop integration is taking additional fields into account in its calculation of the signature that are not being included in the POST message e.g. x_timestamp or x_transaction_type. Could this be the case?

It doesn't look like an issue with the calculation logic or the offsite gateway but with missing variables in the POST message, compared to what is used when they calculate their signature.

**Comment by julianbueno** [comment]
@andrewpaliga is it possible to have a skype call regarding this issue?

**Comment by andrewpaliga** [comment]
There were a few mistakes when transcribing the parameters from the request to the fields map in his code.

1. Numbers were not in single quotes, resulting in them getting truncated when converted to strings (32.20 becomes 32.2, 0.00 becomes 0)
2. There is a trailing whitespace at the end of his shipping address (Should be '2 / 15 Esplanade ‘ instead of '2 / 15 Esplanade’)

Once these changes are made the signature is calculated correctly.

This code works: https://gist.github.com/AnotherJoSmith/8245dbebeb99460b6a0e

Thank you @AnotherJoSmith for looking into this
