### ISSUE TITLE
Help regarding hosted payment sim

### ISSUE THREAD

**Issue by satyendrakumarsingh** [Shopify/hosted-payment-sim#22]
Hello i am using hosted payment SDK i have setup all the thing but not able to understand how to use hosted-payment-sim and how to use x_signature in case of if i have accept all the post request parameter and after success full transaction what i need to do to redirect to shopify store

**Comment by DanWebb** [comment]
Hi @satyendrakumarsingh you should pass all of the parameters received in the POST request from shopify that have a prefix of "x_" apart from the "x_signature". All the params should be merged into a string that's sorted alphabetically with the format "keyvaluekeyvalue...". This string should then be signed using  HMAC-SHA256 with the HMAC key set to the password you enter for your gateway in your shops payment settings, as can be seen under "Gateway Signing Mechanism" [here](https://docs.shopify.com/api/sdks/hosted-payment-sdk/develop-gateway). The result of this signing can then be compared against the x_signature parameter passed from Shopify.

When responding you'll need to redirect the customer to x_url_complete with all the values shown [here](https://docs.shopify.com/api/sdks/hosted-payment-sdk/api-reference/response-values) as query parameters appended to the complete url. Meanwhile creating an async POST request to x_url_callback with the request body set to the same query params you passed in the x_url_complete redirect.

I know this is only repeating what's in the docs but sometimes a second explanation can help, and hopefully this helps you.

**Comment by ShayneP** [comment]
Thanks Dan! Just to add to this Satyendra, you can check out the docs over at https://docs.shopify.com/api/sdks/hosted-payment-sdk/develop-gateway to see a detailed example of this signing mechanism. The relevant example is about halfway down the page.

**Comment by prasanthrubyist** [comment]
@DanWebb , I've same problem in my payment gateway have some required field, But I don't know how to pass shopify required field with my payment required field, Kindly let me know you idea I'm using rails app to develop my payment...Thanks

**Comment by satyendrakumarsingh** [comment]
Hi @prasanthrubyist when shopify store redirect to hosted payment gateway shopify store sends  post(http method) request parameters you have to receive that post request and process all the needed request parameters and after that its up to you that how you can use that request parameters with your payment processor. After that you have to return post(http method) response parameters to the given x_url_complete , x_url_callback. So that shopify store update the order status based on the payment status.

**Comment by prasanthrubyist** [comment]
thank you so much! @satyendrakumarsingh
